name: AI Conversations

on:
  schedule:
    # Run every 30 minutes - script randomly decides whether to execute
    # Creates natural 0-120 minute delays on average
    - cron: '*/30 * * * *'
  
  # Allow manual triggering
  workflow_dispatch:

jobs:
  continue-conversation:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Check if conversation should continue
      id: check_run
      run: |
        # Generate random number 0-99
        RANDOM_NUM=$((RANDOM % 100))
        
        # 50% chance of running (30 min * 2 = 60 min average)
        # This creates 0-120+ minute natural delays
        if [ $RANDOM_NUM -lt 50 ]; then
          echo "run=true" >> $GITHUB_OUTPUT
          echo "🎲 Random check: Executing conversation step (rolled $RANDOM_NUM)"
        else
          echo "run=false" >> $GITHUB_OUTPUT
          echo "🎲 Random check: Skipping this time (rolled $RANDOM_NUM)"
        fi
      shell: bash

    - name: Checkout repository
      if: steps.check_run.outputs.run == 'true'
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      if: steps.check_run.outputs.run == 'true'
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      if: steps.check_run.outputs.run == 'true'
      run: npm install
      
    - name: Create directories
      if: steps.check_run.outputs.run == 'true'
      run: |
        mkdir -p logs/threads
        mkdir -p content/conversations
        
    - name: Continue AI Conversation
      if: steps.check_run.outputs.run == 'true'
      id: conversation_step
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        DEEPSEEK_API_KEY: ${{ secrets.DEEPSEEK_API_KEY }}
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        CLAUDE_API_KEY: ${{ secrets.CLAUDE_API_KEY }}
      run: |
        echo "Continuing AI conversation..."
        
        # Check for closed threads before running
        CLOSED_BEFORE=$(find logs/threads -name "*.json" -exec jq -r 'select(.status == "closed") | .id' {} \; 2>/dev/null | wc -l)
        echo "closed_before=$CLOSED_BEFORE" >> $GITHUB_OUTPUT
        
        # Run the conversation step
        npm run continue-conversation
        
        # Check for closed threads after running
        CLOSED_AFTER=$(find logs/threads -name "*.json" -exec jq -r 'select(.status == "closed") | .id' {} \; 2>/dev/null | wc -l)
        echo "closed_after=$CLOSED_AFTER" >> $GITHUB_OUTPUT
        
        # Check if a conversation ended (new closed thread)
        if [ "$CLOSED_AFTER" -gt "$CLOSED_BEFORE" ]; then
          echo "conversation_ended=true" >> $GITHUB_OUTPUT
          echo "🏁 Conversation ended - will trigger cache refresh"
        else
          echo "conversation_ended=false" >> $GITHUB_OUTPUT
          echo "💬 Conversation continues"
        fi
        
    - name: Check for new files
      if: steps.check_run.outputs.run == 'true'
      id: check_files
      run: |
        if [ "$(git status --porcelain)" ]; then
          echo "changes=true" >> $GITHUB_OUTPUT
          echo "New conversation content created!"
          git status --porcelain
        else
          echo "changes=false" >> $GITHUB_OUTPUT
          echo "No new conversation content"
        fi
        
    - name: Commit and push changes
      if: steps.check_run.outputs.run == 'true' && steps.check_files.outputs.changes == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add logs/ content/
        git commit -m "🤖 AI Conversation Step - $(date -u +%Y-%m-%d_%H:%M)"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Log execution result
      run: |
        if [ "${{ steps.check_run.outputs.run }}" == "true" ]; then
          echo "✅ Conversation step executed"
          if [ "${{ steps.conversation_step.outputs.conversation_ended }}" == "true" ]; then
            echo "🏁 Conversation ended - Vercel will auto-redeploy with fresh UI data"
          fi
        else
          echo "⏭️ Conversation step skipped this time"
        fi 